# Generated by Django 4.0 on 2022-12-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=255, null=True)),
                ('enrolled_students', models.FloatField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_category', models.BooleanField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_year', models.DateTimeField()),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
