# Generated by Django 4.0 on 2022-12-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish_year',
            field=models.DateField(),
        ),
    ]
