# Generated by Django 4.0 on 2022-12-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_publish_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
